version: '3'

services:
  app:
    image: node:14.16.0-stretch
    ports:
      - '3000:3000'
      - '3001:3001'
    container_name: node-app
    tty: true
    volumes:
      - ./app:/app
    working_dir: '/app'